
costs:
  increase_hp: 20
  increase_range_base: 30
  increase_range_per_level: 10
  shoot_base: 10
  shoot_increment: 5
  move: 5
  capture_city: 10
  ramming_speed: 10
  swap_hp_for_energy: 1

daily_energy: 10

starting:
  energy: 0
  hp: 4
  range: 2

rewards:
  energy_cell: 20
  captured_city: 5
  energy_from_hp: 10

attacks:
  ramming_speed:
    damage: 2
    self_damage: 1
  shoot:
    damage: 1

# This is the max on the X and Y axis.
# It calculated as number of players + this number
# This is max X and Y and counting starts at 0 not 1
# So effectively the world size is Players + Number below + 1
world_size_max:
  default: 2
